import { Navigation } from "@/components/navigation/navigation";
import { Toaster } from "@/components/ui/sonner";
import StoreProvider from "@/lib/store/store-provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`${poppins.className} antialiased`}>
          <Navigation />
          {children} <Toaster />
        </body>
      </StoreProvider>
    </html>
  );
}
